#!/bin/bash

# Clean up
rm -rf .flatpak-builder
rm -rf build-dir

# Get the latest firefox build if it doesn't exist
if [ ! -f firefox.tar.bz2 ]; then
    wget -O firefox.tar.bz2 "https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US"
fi

# Get wheels.tar.gz if it doesn't exist
if [ ! -f wheels.tar.gz ]; then
    rm -rf wheels
    docker build -t flatpak-wheels . --no-cache
    docker run --name flatpak-wheels flatpak-wheels

    # Copy wheels.tar.gz to the host
    docker cp flatpak-wheels:/app/wheels.tar.gz wheels.tar.gz

    # Extract the wheels
    tar -xzf wheels.tar.gz

    # Remove the container
    docker rm flatpak-wheels
fi

# Compress the profile
rm -rf profile.tar.gz
tar -czvf profile.tar.gz profile

# Remove old flatpak
flatpak uninstall -y org.flatpak.positron
flatpak-builder --force-clean --install --user build-dir manifest.yml
flatpak run org.flatpak.positron