#!/bin/sh

# Create release folder
mkdir release

# Remove old release
rm -f positron.tar.gz

# Create wheels for the dependencies
# Target version is Python 3.11.9
# This is the version used by org.freedesktop.Platform 23.08
cd src
rm -rf wheels
docker build -t flatpak-wheels . --no-cache
docker run --name flatpak-wheels flatpak-wheels
mkdir -p wheels
docker cp flatpak-wheels:/app/wheels/. wheels
docker rm flatpak-wheels
cd ..

# Copy files
cp -r src/icons release/
cp -r src/profile release/
cp -r src/static release/
cp -r src/templates release/
cp -r src/wheels release/
cp src/app.py release/
cp src/Dockerfile release/
cp src/manifest.yml release/
cp src/org.flatpak.positron.desktop release/
cp src/org.flatpak.positron.sh release/
cp src/build release/
cp src/requirements.txt release/

# Remove the directory
cd release
tar -czf positron.tar.gz *
cd ..
mv release/positron.tar.gz .
rm -rf release

# Done
echo "Done!"
echo "Now you can upload positron.tar.gz to GitHub Releases."
echo "Simply create a new release with the following command:"
echo "gh release create vX.Y positron.tar.gz"
echo "Replace vX.Y with the version number."